## Домашнее задание к лекции "Базовые понятия статистики"



## Обязательная часть 
 
Будем осуществлять работу с непростым [набором данных](https://raw.githubusercontent.com/obulygin/pyda_homeworks/master/statistics_basics/horse_data.csv) о состоянии здоровья лошадей, испытывающих кишечные колики. 
 
### Задание 1. Базовое изучение 
 
Изучить представленный набор данных на основе [описания его столбцов](https://raw.githubusercontent.com/obulygin/pyda_homeworks/master/statistics_basics/horse_data.names) и выбрать 8 столбцов для дальнейшего изучения (среди них должны быть как числовые, так и категориальные). Провести расчет базовых метрик для них, кратко описать результаты. 

### Задание 2. Работа с выбросами 
 
В выбранных числовых столбцах найти выбросы, выдвинуть гипотезы об их причинах и проинтерпретировать результаты. Принять и обосновать решение о дальнейшей работе с ними. 

### Задание 3. Работа с пропусками 
 
Рассчитать количество пропусков для всех выбранных столбцов. Принять и обосновать решение о методе работы с пропусками по каждому столбцу, сформировать датафрейм, в котором пропуски будут отсутствовать.

In [97]:
import pandas as pd
import missingno as msno 
import numpy as np

In [99]:
all_horses_df = pd.read_csv('horse_data.csv', names=['surgery', 'Age', 'Hospital_Number', 'rectal_temperature', 'pulse', 'respiratory_rate', 'temperature_of_extremities', 'peripheral_pulse', 'mucous_membranes', 'capillary_refill_time', 'pain', 'peristalsis', 'abdominal_distension', 'nasogastric_tube', 'nasogastric_reflux', 'nasogastric_reflux_PH', 'rectal_examination_feces', 'abdomen', 'packed_cell_volume', 'total_protein', 'abdominocentesis_appearance', 'abdomcentesis_total_protein', 'outcome', 'surgical_lesion', 'type_of_lesion_1', 'type_of_lesion_2', 'type_of_lesion_3', 'cp_data'])
all_horses_df.head(20)

,surgery,Age,Hospital_Number,rectal_temperature,pulse,respiratory_rate,temperature_of_extremities,peripheral_pulse,mucous_membranes,capillary_refill_time,...,packed_cell_volume,total_protein,abdominocentesis_appearance,abdomcentesis_total_protein,outcome,surgical_lesion,type_of_lesion_1,type_of_lesion_2,type_of_lesion_3,cp_data
0,2,1,530101,38.50,66,28,3,3,?,2,...,45.00,8.40,?,?,2,2,11300,0,0,2
1,1,1,534817,39.2,88,20,?,?,4,1,...,50,85,2,2,3,2,2208,0,0,2
2,2,1,530334,38.30,40,24,1,1,3,1,...,33.00,6.70,?,?,1,2,0,0,0,1
3,1,9,5290409,39.10,164,84,4,1,6,2,...,48.00,7.20,3,5.30,2,1,2208,0,0,1
4,2,1,530255,37.30,104,35,?,?,6,2,...,74.00,7.40,?,?,2,2,4300,0,0,2
5,2,1,528355,?,?,?,2,1,3,1,...,?,?,?,?,1,2,0,0,0,2
6,1,1,526802,37.90,48,16,1,1,1,1,...,37.00,7.00,?,?,1,1,3124,0,0,2
7,1,1,529607,?,60,?,3,?,?,1,...,44.00,8.30,?,?,2,1,2208,0,0,2
8,2,1,530051,?,80,36,3,4,3,1,...,38.00,6.20,?,?,3,1,3205,0,0,2
9,2,9,5299629,38.30,90,?,1,?,1,1,...,40.00,6.20,1,2.20,1,2,0,0,0,1
10,1,1,528548,38.10,66,12,3,3,5,1,...,44.00,6.00,2,3.60,1,1,2124,0,0,1
11,2,1,527927,39.10,72,52,2,?,2,1,...,50.00,7.80,?,?,1,1,2111,0,0,2
12,1,1,528031,37.20,42,12,2,1,1,1,...,?,7.00,?,?,1,2,4124,0,0,2
13,2,9,5291329,38.00,92,28,1,1,2,1,...,37.00,6.10,1,?,2,2,0,0,0,1
14,1,1,534917,38.2,76,28,3,1,1,1,...,46,81,1,2,1,1,2112,0,0,2
15,1,1,530233,37.60,96,48,3,1,4,1,...,45.00,6.80,?,?,2,1,3207,0,0,2
16,1,9,5301219,?,128,36,3,3,4,2,...,53.00,7.80,3,4.70,2,2,1400,0,0,1
17,2,1,526639,37.50,48,24,?,?,?,?,...,?,?,?,?,1,2,0,0,0,2
18,1,1,5290481,37.60,64,21,1,1,2,1,...,40.00,7.00,1,?,1,1,4205,0,0,1
19,2,1,532110,39.4,110,35,4,3,6,?,...,55,8.7,?,?,1,2,0,0,0,2

Преобразовать числовые столбцы в числа, пропуски в Nan, категорийные в слова

In [45]:
# for column in list(all_horses_df.columns):
#     all_horses_df.replace({[column][0]:'?'}, value=None, inplace=True)

In [100]:
all_horses_df['mucous_membranes'] = all_horses_df['mucous_membranes'].replace(to_replace='?', value=np.nan, inplace=True)

In [101]:
all_horses_df

,surgery,Age,Hospital_Number,rectal_temperature,pulse,respiratory_rate,temperature_of_extremities,peripheral_pulse,mucous_membranes,capillary_refill_time,...,packed_cell_volume,total_protein,abdominocentesis_appearance,abdomcentesis_total_protein,outcome,surgical_lesion,type_of_lesion_1,type_of_lesion_2,type_of_lesion_3,cp_data
0,2,1,530101,38.50,66,28,3,3,None,2,...,45.00,8.40,?,?,2,2,11300,0,0,2
1,1,1,534817,39.2,88,20,?,?,None,1,...,50,85,2,2,3,2,2208,0,0,2
2,2,1,530334,38.30,40,24,1,1,None,1,...,33.00,6.70,?,?,1,2,0,0,0,1
3,1,9,5290409,39.10,164,84,4,1,None,2,...,48.00,7.20,3,5.30,2,1,2208,0,0,1
4,2,1,530255,37.30,104,35,?,?,None,2,...,74.00,7.40,?,?,2,2,4300,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,1,1,533886,?,120,70,4,?,None,2,...,55,65,?,?,3,2,3205,0,0,2
296,2,1,527702,37.20,72,24,3,2,None,2,...,44.00,?,3,3.30,3,1,2208,0,0,1
297,1,1,529386,37.50,72,30,4,3,None,1,...,60.00,6.80,?,?,2,1,3205,0,0,2
298,1,1,530612,36.50,100,24,3,3,None,1,...,50.00,6.00,3,3.40,1,1,2208,0,0,1
299,1,1,534618,37.2,40,20,?,?,None,?,...,36,62,1,1,3,2,6112,0,0,2